News fragment
Zsteven44/PUBG-Companion pull request #52
Opened 2017-05-23 05:05 UTC by Zsteven44

2017-05-23 12:51 UTC, zafrani requested changes
Looks good

2017-05-23 12:51 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/adapters/NewsAdapter.java
> +    public NewsAdapter() {
This empty constructor isn't needed

2017-05-23 12:51 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/utils/PUBGNewsFetch.java
> +            document = Jsoup.connect("https://www.playbattlegrounds.com/news.pu").get();
This URL can go in our Constants.java file.

2017-05-23 12:51 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/utils/PUBGNewsFetch.java
> +                final String title = row.select(".title").text();
I would store all of these strings like .title as private static final strings of this class. Each for loop will create a new instance of the same value.

2017-05-23 12:51 UTC, zafrani commented on app/src/main/res/layout/row_item_news.xml
> +        android:layout_width="150dp"
I don't think we should limit the width. large screens will look funny.

2017-05-23 12:51 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/fragments/NewsFragment.java
> +    private RecyclerView recyclerView;
This should be Nullable

2017-05-23 12:51 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/fragments/NewsFragment.java
> +    private NewsAdapter adapter;
This should be nullable

2017-05-23 12:51 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/fragments/NewsFragment.java
> +        return inflater.inflate(R.layout.fragment_news, container,false);
BaseFragment uses butterknife now. I think you need to merge develop into this branch to get its changes.

2017-05-23 12:51 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/fragments/NewsFragment.java
> +        recyclerView = (RecyclerView) view.findViewById(R.id.fragment_news_recyclerview);
After you update your branch with develop you should use butterknife to bind this

2017-05-23 12:51 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/utils/PUBGNewsFetch.java
> +    public PUBGNewsFetch(@NonNull final NewsAdapter adapter) {
This is good. However now PUBGNewsFetch forces the class that uses it to provide an adapter. There may be cases where an adapter isn't needed. To simplify things you can instead define a Listener interface inside of PUBGNewsFetch which contains an update method that receives News. Make the fragment implement that interface and update the adapter there.

2017-05-23 23:19 UTC, zafrani requested changes

2017-05-23 23:19 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/adapters/NewsAdapter.java
> +    private News news = new News();
This can be final Nonull

2017-05-23 23:19 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/adapters/NewsAdapter.java
> +    public void onBindViewHolder(NewsItemViewHolder holder, int position) {
finals

2017-05-23 23:19 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/adapters/NewsAdapter.java
> +    public NewsItemViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
finals

2017-05-23 23:19 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/adapters/NewsAdapter.java
> +        return news == null ? 0 : news.size();
news should never be null

2017-05-23 23:19 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/adapters/NewsAdapter.java
> +        @BindView(R.id.row_item_description)
Don't use butterknife for view holders. You can make the fields private final and find by id in the constructor

2017-05-23 23:19 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/fragments/NewsFragment.java
> +        super.onDestroy();
before calling super you should check if the recyclerview is null, if not  call `recyclerView.setAdapter(null)` reduce any chances of a memory leak.

2017-05-23 23:19 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/fragments/NewsFragment.java
> +        super.onDestroy();
Also set the adapter to null

2017-05-23 23:19 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/utils/PUBGNewsFetch.java
> +    public interface PUBGNewsListener {
Just call this Listener. When you implement it you will be forced to use its parent class which makes it obvious it is for PUBGNewsFetch

2017-05-23 23:19 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/utils/PUBGNewsFetch.java
> +    public PUBGNewsListener delegate = null;
Make this final nonnull and pass it from the constructor.

2017-05-23 23:19 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/fragments/NewsFragment.java
> +    public PUBGNewsFetch.PUBGNewsListener delegate;
You don't need this variable.

2017-05-23 23:25 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/adapters/NewsAdapter.java
> +        @BindView(R.id.row_item_description)
And nonnull

2017-05-23 23:41 UTC, Zsteven44 commented on app/src/main/java/tech/zafrani/companionforpubg/utils/PUBGNewsFetch.java
> +    public PUBGNewsListener delegate = null;
Can you explain this?  The asynctask doesn't use a constructor.

2017-05-24 13:37 UTC, zafrani requested changes

2017-05-24 13:37 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/fragments/NewsFragment.java
> +            recyclerView.setAdapter(null);
this needs to be done before super.onDestroy().

super.onDestroy will call the BaseFragments onDestroy method which uses butterknifes unbind method. The unbind method sets anything binded with butterknife to null. So after super.ondestroy recyclerview will be null but the instance of it in memory will still hold a reference to the adapter.

2017-05-24 23:38 UTC, zafrani approved these changes

2017-05-24 23:38 UTC, merged