Newsdetails
Zsteven44/PUBG-Companion pull request #64
Opened 2017-05-28 04:50 UTC by Zsteven44

2017-05-28 14:54 UTC, zafrani requested changes

2017-05-28 14:54 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/activities/NewsDetailActivity.java
> +        super.onDestroy();
This can be erased as it does nothing

2017-05-28 14:54 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/fragments/NewsDetailFragment.java
> +        final String newsSrc = args.getString(ARG_NEWS_SRC);
you need to make sure this isn't null too.

2017-05-28 14:54 UTC, zafrani commented on app/src/main/java/tech/zafrani/companionforpubg/fragments/NewsDetailFragment.java
> +    WebView newsWebView;
this should go above the functions in this file and below the statics.

2017-05-28 16:47 UTC, Zsteven44 commented
don't merge this yet

2017-05-30 20:51 UTC, zafrani commented
@Zsteven44 This needs to be zoomable and show the actionbar with a back button on top from the webview screen

2017-05-30 22:55 UTC, zafrani approved these changes

2017-05-30 22:55 UTC, merged